[tools]
deno = "latest"
go = "1"
node = "24"
npm = "openai/codex"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@companion-ai/feynman" = "0.2.52"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:@playwright/cli" = "latest"
"npm:@tailwindcss/language-server" = "0.14.26"
"npm:@vue/language-server" = "2.2.12"
"npm:agent-browser" = "latest"
"npm:pnpm" = "11"
"npm:typescript" = "6"
"npm:typescript-language-server" = "5"
"npm:vscode-langservers-extracted" = "4.10.0"
"npm:yaml-language-server" = "latest"
pnpm = "10"
python = "3.11"

[settings]
idiomatic_version_file_enable_tools = []
